version: "3.8"
services:
  service_01:
    container_name: service_01
    # image: dbrownless1/project_02_service_01:${app_version}
    image: dbrownless1/project_02_service_01
    build: ./service_01
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
  service_02:
    container_name: service_02
    # image: dbrownless1/project_02_service_02:${app_version}
    image: dbrownless1/project_02_service_02
    build: ./service_02
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
  service_03:
    container_name: service_03
    # image: dbrownless1/project_02_service_03:${app_version}
    image: dbrownless1/project_02_service_03
    build: ./service_03
    ports:
      - target: 5002
        published: 5002
        protocol: tcp
  service_04:
    container_name: service_04
    # image: dbrownless1/project_02_service_04:${app_version}
    image: dbrownless1/project_02_service_04
    build: ./service_04
    ports:
        - target: 5003
          published: 5003
          protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
