- name: add jenkins user
  user:
    name: jenkins
    groups: docker
    shell: /bin/bash
    append: true

- name: Init Swarm
  community.general.docker.swarm:
    state: present
  register: swarm_info