---
- name: install nginx
  become: true
  apt:
    pkg:
    - nginx
    state: latest
    update_cache: true
  
- name: start nginx service
  become: true
  service:
    name: nginx
    state: started

- name: 'configure load-balancer'
  become: true
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: 'reload nginx'
