all:
  children:
    managers:
      hosts:
        manager:     
    workers:
      hosts:
        worker1:
        worker2:
  vars:
    ansible_user: brown
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    users:
      - username: jenkins
